### ISSUE TITLE
"file does not exit" error on windows, while english version is ok to run

### ISSUE THREAD

**Issue by Yiyiyimu** [gobyexample-cn/gobyexample#59]
Thank you for the translation, they are so great!

When I build it locally, I come to the following file missing error, while the file is actually at that certain place. I noticed the code to call this file is the same, which is tools/generate.go, with English version, and I could compile correctly in original English version, so I'm not so sure where this problem come from.

### error info
```
panic: exec: "./vendor/pygments/pygmentize": file does not exist

goroutine 1 [running]:
main.check(...)
        C:/somepath/gobyexample/tools/generate.go:32
main.pipe(0x7c1fa5, 0x1c, 0xc000079c90, 0x4, 0x4, 0xc00023c07b, 0xc, 0x7b8c03, 0x1, 0xc00020a510)
        C:/somepath/gobyexample/tools/generate.go:55 +0x300
main.cachedPygmentize(0x7b8d14, 0x2, 0xc00023c07b, 0xc, 0xc000248100, 0x7b)
        C:/somepath/gobyexample/tools/generate.go:88 +0x2cb
main.parseAndRenderSegs(0xc00022e100, 0x19, 0x5, 0x0, 0x4, 0x0, 0x0)
        C:/somepath/gobyexample/tools/generate.go:225 +0x13f
main.parseExamples(0x7c01cb, 0x17, 0xc0000106c0)
        C:/somepath/gobyexample/tools/generate.go:271 +0x918
main.main()
        C:/somepath/gobyexample/tools/generate.go:334 +0x303
exit status 2
```

### Environment
System: Windows10 Pro
Bash: Git Bash

**Comment by everyx** [comment]
If you still have this problem, please reopen it.
